apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ambari-based-hadoop-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "ambari-based-hadoop-exporter.name" . }}
    helm.sh/chart: {{ template "ambari-based-hadoop-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "ambari-based-hadoop-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "ambari-based-hadoop-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
{{ toYaml .Values.environmentVariables| indent 12 }}
            - name: "Secrets__Path"
              value: "/secrets{{ .Values.keyvault.secretsMountPath }}/"
            - name: "PrometheusExporterConfiguration__Port"
              value: "{{ .Values.service.targetPort }}"
            - name: "LivenessConfiguration__SamplingPeriodInSeconds"    # Used to perform update the liveness state against the configured Cluster every 60 seconds.
              value: "60"
          livenessProbe:
            exec:
              command: 
                - rm
                - /tmp/healthy
            initialDelaySeconds: 75
            periodSeconds: 120
            timeoutSeconds: 5
          resources:
{{ required "missing resources" .Values.resources | toYaml | indent 12 }}
          volumeMounts:
            - name: secrets-folder
              mountPath: {{ .Values.keyvault.secretsMountPath }}
              readOnly: true
      initContainers:
        - name: keyvault-agent
          image: "{{ .Values.keyvault.acsKVAgent.image.name }}:{{ .Values.keyvault.acsKVAgent.image.tag }}"
          env:
          - name: VAULT_BASE_URL
            value: {{ .Values.keyvault.vaultUrl }}
          - name: SECRETS_FOLDER
            value: {{ .Values.keyvault.secretsMountPath }}
          - name: USE_MSI
            value: "true"
          - name: SECRETS_KEYS
            value: {{ .Values.keyvault.secrets }}
            {{- if .Values.keyvault.azureAuthorityServer }}
          - name: AZURE_AUTHORITY_SERVER
            value: {{ .Values.keyvault.azureAuthorityServer }}
            {{- end }}
            {{- if .Values.keyvault.vaultResourceName }}
          - name: VAULT_RESOURCE_NAME
            value: {{ .Values.keyvault.vaultResourceName }}
            {{- end }}
          volumeMounts:
          - name: secrets-folder
            mountPath: {{ .Values.keyvault.secretsMountPath }}
      volumes:
        - name: secrets-folder
          emptyDir:
            medium: Memory  # we want the secrets to reside only in-memory
      {{- if .Values.podPriorityClass }}
      priorityClassName: {{ .Values.podPriorityClass }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}